[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "cd frontend && npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd frontend && npm run preview -- --host 0.0.0.0 --port ${PORT:-5174}"
